language: java
jdk:
    - oraclejdk8
services:
    - mysql
    - redis-server
before_install:
    - openssl aes-256-cbc -K $encrypted_58aadde3b7da_key -iv $encrypted_58aadde3b7da_iv -in src/main/resources/application.yml.enc -out src/main/resources/application.yml -d
    - mysql -e 'CREATE DATABASE meow;'
install:
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - cd src/main/web
    - npm install
    - npm run build
sudo: required
