spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/Meow?useUnicode=yes&characterEncoding=UTF-8
    username: meow
    password: meow

  jpa:
    database-platform: MySQL5InnoDB
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework.web: DEBUG

  thymeleaf:
    mode: LEGACYHTML5
    cache: true